<a href="https://colab.research.google.com/github/Kuboz46/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Norma wektora, długość wektora w R^2

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [5]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa w R^n

In [7]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

Odległość dwóch punktów w przestrzeni R^n

In [9]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

Mnożenie macierzy

In [11]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [15]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [13]:
Z.shape

(2, 1)

Przykład 2

In [16]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [17]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [18]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)

9.999999999999998

Ślad macierzy

In [19]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa

In [20]:
np.eye(5, dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna

In [23]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [26]:
np.set_printoptions(precision = 4, suppress = True)

np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [28]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [29]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [30]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [31]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [33]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [34]:
X.shape

(2, 1)